"""Split the recipe table into multiple

Revision ID: ce119285f2bd
Revises: 8aca30e65f41
Create Date: 2026-02-06 09:14:04.552991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce119285f2bd'
down_revision: Union[str, Sequence[str], None] = '8aca30e65f41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('main', sa.Text(), nullable=True),
    sa.Column('sub', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('kitchens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('main', sa.Text(), nullable=True),
    sa.Column('sub', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('main', sa.Text(), nullable=True),
    sa.Column('sub', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_courses',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('recipe_id', 'course_id')
    )
    op.create_table('recipe_ingredients',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('unit_abbreviation', sa.Text(), nullable=True),
    sa.Column('postfix', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('recipe_id', 'ingredient_id')
    )
    op.create_index('ix_recipe_ingredients_ingredient_id', 'recipe_ingredients', ['ingredient_id'], unique=False)
    op.create_table('recipe_kitchens',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('kitchen_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kitchen_id'], ['kitchens.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('recipe_id', 'kitchen_id')
    )
    op.create_table('recipe_tags',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('recipe_id', 'tag_id')
    )
    op.add_column('recipes', sa.Column('preparation_time', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('total_time', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('kcal', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('fat', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('saturated_fat', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('carbs', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('protein', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('fibers', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('salt', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('persons', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('url', sa.Text(), nullable=True))
    op.add_column('recipes', sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('recipes', sa.Column('requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('recipes', sa.Column('difficulty', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('recipes', 'ingredients')
    op.drop_column('recipes', 'tags')
    op.drop_column('recipes', 'kitchen')
    op.drop_column('recipes', 'course')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('course', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False))
    op.add_column('recipes', sa.Column('kitchen', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False))
    op.add_column('recipes', sa.Column('tags', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False))
    op.add_column('recipes', sa.Column('ingredients', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False))
    op.drop_column('recipes', 'difficulty')
    op.drop_column('recipes', 'requirements')
    op.drop_column('recipes', 'steps')
    op.drop_column('recipes', 'url')
    op.drop_column('recipes', 'persons')
    op.drop_column('recipes', 'salt')
    op.drop_column('recipes', 'fibers')
    op.drop_column('recipes', 'protein')
    op.drop_column('recipes', 'carbs')
    op.drop_column('recipes', 'saturated_fat')
    op.drop_column('recipes', 'fat')
    op.drop_column('recipes', 'kcal')
    op.drop_column('recipes', 'total_time')
    op.drop_column('recipes', 'preparation_time')
    op.drop_table('recipe_tags')
    op.drop_table('recipe_kitchens')
    op.drop_index('ix_recipe_ingredients_ingredient_id', table_name='recipe_ingredients')
    op.drop_table('recipe_ingredients')
    op.drop_table('recipe_courses')
    op.drop_table('tags')
    op.drop_table('kitchens')
    op.drop_table('ingredients')
    op.drop_table('courses')
    # ### end Alembic commands ###
